### ISSUE TITLE
Routes Command broken as of Rails 7.1+

### ISSUE THREAD

**Issue by dtflowers** [amatsuda/routes_lazy_routes#12]
**Description**
It appears the monkeypatch to eager load routes before running this command that was introduced [here](https://github.com/amatsuda/routes_lazy_routes/issues/2) is no longer being applied as of Rails 7.1.

**Repro**
1. Install this gem on on a project with a Rails version of 7.1+ (our app is currently on 7.1.2 fwiw).
2. Without forcing eager loading, run `rails routes` command, and you will see this output:
> You don't have any routes defined!
> 
> Please add some routes in config/routes.rb.
3. To confirm, if you run this same command with `EAGER_LOAD=1` set in your environment, the command will successfully load the routes before executing.
4. It will also succeed if you remove this gem entirely.

I am still trying to comb through what changed in this version causing this to break, but it seems clear that the core issue is that the routes are not being eager loaded before executing the command. Any ideas?

**Comment by r7kamura** [comment]
I ran into the same problem when I was trying to update our Rails application from Rails 7.0 to 7.1. I am also doing some research to see if there is anything I can do, but so far I have not come up with any good ideas 🤔
