### ISSUE TITLE
`$ rails routes` doesn't show any routes in rails 6

### ISSUE THREAD

**Issue by tricknotes** [amatsuda/routes_lazy_routes#2]
It seems `rails routes` command needs `RoutesLazyRoutes.eager_load!` to be called, but it doesn't.

``` console
$ bin/rails -v
Rails 6.0.3.4
$ cat config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
end
$ bin/rake routes
Prefix Verb URI Pattern Controller#Action
  root GET  /           welcome#index
$ bin/rails routes
You don't have any routes defined!

Please add some routes in config/routes.rb.

For more information about routes, see the Rails guide: https://guides.rubyonrails.org/routing.html.
```

I confirmed that https://github.com/tricknotes/routes_lazy_routes/commit/a5e5d8c90e4efd88d8c88b6f8942dd9c526a0b6c works for me.
However, I'm not sure it is right way or not...

**Comment by amatsuda** [comment]
@tricknotes Thank you for letting me know this!
Just made a release (0.3.2) with a fix based on your patch (it doesn't look very nice indeed, but I also couldn't come up with any better solution...).
Let's see if it works.

**Comment by tricknotes** [comment]
Great thanks!
It seems working fine on my local 🤘
