### ISSUE TITLE
Remove Rails meta-gem dependency in favor of more specific dependency? Railties?

### ISSUE THREAD

**Issue by bf4** [amatsuda/routes_lazy_routes#3]
Would you be up for PR to remove the strict gem dependency on the Rails meta-gem, and perhaps replace it with railties and actionpack?  As it is, adding this gem to our Gemfile requires us to install action_cable, etc which we otherwise wouldn't need to install.

**Comment by amatsuda** [comment]
@bf4 Just did so, and made the 0.4.0 gem release. Thank you for the suggestion!
